//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.KeHoachNam {
    
    
    public partial class TanSuat_Input {
        
        /// <summary>
        /// ID8_10F06128_E9E7_4FCB_8188_9A61911893DE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_10F06128_E9E7_4FCB_8188_9A61911893DE;
        
        /// <summary>
        /// ID6_A11FB5E1_3DAC_4DDA_950F_9A976E43BF3F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_A11FB5E1_3DAC_4DDA_950F_9A976E43BF3F;
    }
}
