//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.ViPham {
    
    
    public partial class HanhViViPham_Input {
        
        /// <summary>
        /// ID8_273EA18C_C3FD_4C7D_A9A6_BEDB6C7BE70A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_273EA18C_C3FD_4C7D_A9A6_BEDB6C7BE70A;
        
        /// <summary>
        /// ID8_B9AEBA83_3618_4D64_8848_D38B1792CBAE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_B9AEBA83_3618_4D64_8848_D38B1792CBAE;
        
        /// <summary>
        /// ID8_67A48D08_05D6_4F52_B155_84B9284A978D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_67A48D08_05D6_4F52_B155_84B9284A978D;
    }
}
