//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.ViPham {
    
    
    public partial class NghiepVuViPham_Input {
        
        /// <summary>
        /// ID8_21D3AA58_E232_4906_AE6E_CE516D908910 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_21D3AA58_E232_4906_AE6E_CE516D908910;
        
        /// <summary>
        /// ID8_569D7AEC_742E_4918_B1F6_282FC393DF93 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_569D7AEC_742E_4918_B1F6_282FC393DF93;
    }
}
