//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.ViPham {
    
    
    public partial class NhomHanhViViPham_Input {
        
        /// <summary>
        /// ID8_4DCBD2E6_4C65_4FE3_839C_C54C79AADB74 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_4DCBD2E6_4C65_4FE3_839C_C54C79AADB74;
        
        /// <summary>
        /// ID8_222D4F00_4E85_4CA6_B052_3287FCFE0FA4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_222D4F00_4E85_4CA6_B052_3287FCFE0FA4;
        
        /// <summary>
        /// ID8_D94F69C8_D205_4FB3_9305_593B67B70C10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_D94F69C8_D205_4FB3_9305_593B67B70C10;
    }
}
