//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.HinhThucXuLy {
    
    
    public partial class HinhThucXuLyQuyDinhNoiBo_Input {
        
        /// <summary>
        /// ID8_44A8E83C_8C52_44AC_BA97_F2EFF16F6DF6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_44A8E83C_8C52_44AC_BA97_F2EFF16F6DF6;
        
        /// <summary>
        /// ID8_6F3C2CCE_2C94_40A9_A28D_048BDC514134 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_6F3C2CCE_2C94_40A9_A28D_048BDC514134;
    }
}
