//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.HinhThucXuLy {
    
    
    public partial class HinhThucXuLyLuatLaoDong_Input {
        
        /// <summary>
        /// ID8_BFB564E4_2E62_4755_AB4C_26391E21BB43 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_BFB564E4_2E62_4755_AB4C_26391E21BB43;
        
        /// <summary>
        /// ID8_36DD6FCE_361D_4643_B04E_46CA161971A0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_36DD6FCE_361D_4643_B04E_46CA161971A0;
    }
}
