//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.ChucDanh {
    
    
    public partial class BanDanhGia_Input {
        
        /// <summary>
        /// drpPhongBan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList drpPhongBan;
        
        /// <summary>
        /// ID8_2D5C80C0_39AC_478A_A79E_D9F38D705786 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_2D5C80C0_39AC_478A_A79E_D9F38D705786;
        
        /// <summary>
        /// ID8_AF348562_CD57_4F06_B97A_044B6E25C8CC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_AF348562_CD57_4F06_B97A_044B6E25C8CC;
        
        /// <summary>
        /// ID6_38F9D072_1864_43C1_92FC_8DDABEDC8DEB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_38F9D072_1864_43C1_92FC_8DDABEDC8DEB;
    }
}
