//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.ChucDanh {
    
    
    public partial class QLNhansuKTNB_Input {
        
        /// <summary>
        /// ID8_F9B2BEB9_B3F4_4878_B718_547915007D0D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_F9B2BEB9_B3F4_4878_B718_547915007D0D;
        
        /// <summary>
        /// ID8_6CF20676_81A6_4766_9854_9FD8EE4F6B26 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_6CF20676_81A6_4766_9854_9FD8EE4F6B26;
        
        /// <summary>
        /// ID3_02B2A5FC_6E59_4917_83EE_3A26DA31D59C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID3_02B2A5FC_6E59_4917_83EE_3A26DA31D59C;
        
        /// <summary>
        /// ID8_385CD97C_1A72_4AF1_9472_53EE5EB272BE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_385CD97C_1A72_4AF1_9472_53EE5EB272BE;
        
        /// <summary>
        /// ID8_558DD2DC_841B_4368_A426_B84F01079086 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_558DD2DC_841B_4368_A426_B84F01079086;
        
        /// <summary>
        /// ID8_936D771B_D880_4A1C_8D6E_42C571C2853C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_936D771B_D880_4A1C_8D6E_42C571C2853C;
        
        /// <summary>
        /// ID3_D7E84FA3_B6A9_40D0_B504_291E7F11C3C1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID3_D7E84FA3_B6A9_40D0_B504_291E7F11C3C1;
        
        /// <summary>
        /// ID8_74DC98E4_62C9_45C3_A6B1_0BF380DCB9F1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_74DC98E4_62C9_45C3_A6B1_0BF380DCB9F1;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
