//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.ChucDanh {
    
    
    public partial class QLQuytrinhActivitySanpham_Input {
        
        /// <summary>
        /// ID8_1A265085_0B1B_4FE5_B7AF_51EEF89B6474 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_1A265085_0B1B_4FE5_B7AF_51EEF89B6474;
        
        /// <summary>
        /// ID8_DA131AD9_234F_43CE_BBED_ED408543A23E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_DA131AD9_234F_43CE_BBED_ED408543A23E;
        
        /// <summary>
        /// ID8_4E6F4C58_F130_451B_9779_3434753A53BA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_4E6F4C58_F130_451B_9779_3434753A53BA;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
