//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.DanhMuc.ChucDanh {
    
    
    public partial class QuymoLoaiDTKT_Input {
        
        /// <summary>
        /// ID8_3661C77F_A22A_440D_8D32_FE472A117505 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_3661C77F_A22A_440D_8D32_FE472A117505;
        
        /// <summary>
        /// ID8_48163DD4_9F4B_4AC4_A1B9_A25BBB1F0EA2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_48163DD4_9F4B_4AC4_A1B9_A25BBB1F0EA2;
        
        /// <summary>
        /// ID8_A3AFE5F3_3412_4418_854C_BD17EFAFD6BE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_A3AFE5F3_3412_4418_854C_BD17EFAFD6BE;
        
        /// <summary>
        /// ID8_396C3AD1_2349_4CBA_94E7_108EE6B9AE6D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_396C3AD1_2349_4CBA_94E7_108EE6B9AE6D;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
