//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.DMS {
    
    
    public partial class ChiTietHoSoPhanTichSoBo_Load {
        
        /// <summary>
        /// ID8_AC4286FB_5B38_47C4_93F0_E075F171D8FC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_AC4286FB_5B38_47C4_93F0_E075F171D8FC;
        
        /// <summary>
        /// ID8_CBA39743_AA0E_4965_9201_BE3BB5CF710A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_CBA39743_AA0E_4965_9201_BE3BB5CF710A;
        
        /// <summary>
        /// ID8_05B1B244_C5E3_4199_B523_96A3E131D83D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_05B1B244_C5E3_4199_B523_96A3E131D83D;
    }
}
