//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.DMS {
    
    
    public partial class DotKiemToan_Load {
        
        /// <summary>
        /// ID8_23FB0D9B_6A02_44B0_A1AA_CEFA895CD9C1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID8_23FB0D9B_6A02_44B0_A1AA_CEFA895CD9C1;
        
        /// <summary>
        /// ID8_63A0C4B1_2088_4994_B891_2FF65EB20265 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_63A0C4B1_2088_4994_B891_2FF65EB20265;
        
        /// <summary>
        /// ID8_737694DF_DE17_4FF9_AE15_70E197C83593 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_737694DF_DE17_4FF9_AE15_70E197C83593;
        
        /// <summary>
        /// ID8_2A4CA2AD_0282_4D57_86AC_D973D281EF54 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_2A4CA2AD_0282_4D57_86AC_D973D281EF54;
        
        /// <summary>
        /// ID8_06991CFA_158B_4460_8B7E_EC010C14DFE4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_06991CFA_158B_4460_8B7E_EC010C14DFE4;
        
        /// <summary>
        /// ID8_B23A439D_95D3_466E_8AD1_CDDAC260CB27 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_B23A439D_95D3_466E_8AD1_CDDAC260CB27;
        
        /// <summary>
        /// ID8_7D31CEB6_69CC_4F8E_9BE6_38762D7C30C6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_7D31CEB6_69CC_4F8E_9BE6_38762D7C30C6;
        
        /// <summary>
        /// ID8_46C1BE6C_68F3_47B9_B0FB_DEC78831AEFF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_46C1BE6C_68F3_47B9_B0FB_DEC78831AEFF;
    }
}
