//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.DMS {
    
    
    public partial class KeHoachKiemToanNam_Load {
        
        /// <summary>
        /// ID8_3F979CD0_8B2C_4167_A5B2_1016C85D0978 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_3F979CD0_8B2C_4167_A5B2_1016C85D0978;
        
        /// <summary>
        /// ID8_D8A29EE8_E564_4DDC_ACCA_BAE990A5FB53 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_D8A29EE8_E564_4DDC_ACCA_BAE990A5FB53;
    }
}
