//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.DMS {
    
    
    public partial class PhatHienViPham_Load {
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// ID8_7222867E_EC9C_46FF_BC71_20873B7EBD37 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_7222867E_EC9C_46FF_BC71_20873B7EBD37;
        
        /// <summary>
        /// ID8_1C98F56A_9CFE_410E_882C_7AB370D99A78 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_1C98F56A_9CFE_410E_882C_7AB370D99A78;
        
        /// <summary>
        /// txtCongViec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCongViec;
        
        /// <summary>
        /// ID8_D5637BAF_54F3_4724_9E3B_8543EB93509A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_D5637BAF_54F3_4724_9E3B_8543EB93509A;
        
        /// <summary>
        /// ID8_A4C22F5B_2271_46D8_AD8D_B88B7399317A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_A4C22F5B_2271_46D8_AD8D_B88B7399317A;
        
        /// <summary>
        /// ID8_10A26FD0_3309_4E1E_B83B_AC55E8194C2F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_10A26FD0_3309_4E1E_B83B_AC55E8194C2F;
        
        /// <summary>
        /// ID8_0480690F_6373_4AC3_BA8C_FF61AA8763B7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_0480690F_6373_4AC3_BA8C_FF61AA8763B7;
        
        /// <summary>
        /// ID8_5D74DB08_2EFD_47DC_8970_0C015F89F05D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_5D74DB08_2EFD_47DC_8970_0C015F89F05D;
        
        /// <summary>
        /// ID8_06271BD7_653E_4EF4_826F_991A408A2074 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_06271BD7_653E_4EF4_826F_991A408A2074;
        
        /// <summary>
        /// ID8_483F188D_3325_4EAB_8A9E_24B187EA5BE1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_483F188D_3325_4EAB_8A9E_24B187EA5BE1;
        
        /// <summary>
        /// ID8_CF188F52_E26C_4FA4_B3EA_566E64D68E35 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_CF188F52_E26C_4FA4_B3EA_566E64D68E35;
        
        /// <summary>
        /// ID8_28F7AE8F_FAA5_4548_A761_E5ABB99A3FDC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_28F7AE8F_FAA5_4548_A761_E5ABB99A3FDC;
        
        /// <summary>
        /// ID8_85561BD3_7EA6_4078_8D9E_92555EE9D5D4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_85561BD3_7EA6_4078_8D9E_92555EE9D5D4;
        
        /// <summary>
        /// ID8_9964AFC3_D7D3_4EAE_9E97_A06491986376 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_9964AFC3_D7D3_4EAE_9E97_A06491986376;
        
        /// <summary>
        /// ID8_0823B6FB_A376_4922_A3D2_F9DFE428F132 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_0823B6FB_A376_4922_A3D2_F9DFE428F132;
        
        /// <summary>
        /// ID8_5DBE8B67_B15B_44B0_B338_BFF9A5893E38 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_5DBE8B67_B15B_44B0_B338_BFF9A5893E38;
        
        /// <summary>
        /// ID8_BCB66023_B645_4ACE_9BDA_739E36D2EA91 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_BCB66023_B645_4ACE_9BDA_739E36D2EA91;
        
        /// <summary>
        /// ID8_D4E3708C_A637_4737_95DD_5BE0791CF5AB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_D4E3708C_A637_4737_95DD_5BE0791CF5AB;
        
        /// <summary>
        /// ID8_DE9FFB27_2B1D_448B_9F47_BFC8BA38E980 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_DE9FFB27_2B1D_448B_9F47_BFC8BA38E980;
        
        /// <summary>
        /// ID8_EC4C86B7_B065_43D0_B6DE_42A3429A7B3C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_EC4C86B7_B065_43D0_B6DE_42A3429A7B3C;
        
        /// <summary>
        /// ID8_384E8A87_E6C5_46B2_B855_1EE0C954255B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_384E8A87_E6C5_46B2_B855_1EE0C954255B;
        
        /// <summary>
        /// ID8_A75D10D9_AC94_41B8_9BDC_0B5DFBB25ECC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_A75D10D9_AC94_41B8_9BDC_0B5DFBB25ECC;
        
        /// <summary>
        /// ID8_D1FA20D3_1754_4FE9_B05E_BE912E977F34 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_D1FA20D3_1754_4FE9_B05E_BE912E977F34;
        
        /// <summary>
        /// ID8_01B25AC2_2EAA_4779_A8AD_AFC45EE8C0AB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_01B25AC2_2EAA_4779_A8AD_AFC45EE8C0AB;
        
        /// <summary>
        /// ID8_246A4FCC_FC59_4900_8ACF_9DBB2323E14A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_246A4FCC_FC59_4900_8ACF_9DBB2323E14A;
        
        /// <summary>
        /// ID8_1D5CAE34_E7C1_4539_9EA2_0F7C40454DA8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_1D5CAE34_E7C1_4539_9EA2_0F7C40454DA8;
        
        /// <summary>
        /// ID8_CDD9A94A_43F3_4289_835C_32634683D866 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_CDD9A94A_43F3_4289_835C_32634683D866;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
        
        /// <summary>
        /// DaNhanXetNguoiDuyet1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox DaNhanXetNguoiDuyet1;
        
        /// <summary>
        /// ID8_75AF3ED2_78F6_4DAE_BB20_157920BAC865 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_75AF3ED2_78F6_4DAE_BB20_157920BAC865;
        
        /// <summary>
        /// gridTuChoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1WebGrid.C1WebGrid gridTuChoi;
    }
}
