//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class BoTieuChiDanhGiaCLKTV_Load {
        
        /// <summary>
        /// ID8_FB2F72B5_27DC_458B_BB16_D7DC09E4C7B2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_FB2F72B5_27DC_458B_BB16_D7DC09E4C7B2;
        
        /// <summary>
        /// ID8_02CCDE67_5D27_4DF2_BA7C_FD8B7DDE2D74 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_02CCDE67_5D27_4DF2_BA7C_FD8B7DDE2D74;
        
        /// <summary>
        /// ID8_323CF8C8_06B8_4F57_8DC4_01C70E704051 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_323CF8C8_06B8_4F57_8DC4_01C70E704051;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
