//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class CongViecTheoQuyMoDotKiemSoat_Load {
        
        /// <summary>
        /// ID8_D0C2F31F_A7AA_4164_941C_451AFB331A46 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_D0C2F31F_A7AA_4164_941C_451AFB331A46;
        
        /// <summary>
        /// ID8_E3045993_F205_47E3_900B_E78BCF4EC411 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_E3045993_F205_47E3_900B_E78BCF4EC411;
        
        /// <summary>
        /// ID6_0B2F41A9_0F2A_4FD1_B116_3FF605CB71E4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_0B2F41A9_0F2A_4FD1_B116_3FF605CB71E4;
        
        /// <summary>
        /// ID6_5AC88958_61BE_403E_AFA2_5EAB6AE2C3F7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_5AC88958_61BE_403E_AFA2_5EAB6AE2C3F7;
        
        /// <summary>
        /// ID6_0DAE6861_DD7B_458D_B257_76F38A840B3B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_0DAE6861_DD7B_458D_B257_76F38A840B3B;
        
        /// <summary>
        /// ID6_A5AF2CEF_FDDE_430D_A90E_7E6B5CB3FDD9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_A5AF2CEF_FDDE_430D_A90E_7E6B5CB3FDD9;
        
        /// <summary>
        /// ID6_BD07C2F0_3130_4623_BB3A_A16B05A33D9A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_BD07C2F0_3130_4623_BB3A_A16B05A33D9A;
        
        /// <summary>
        /// ID6_60555BB9_EE34_485E_878D_D2B7BF154005 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_60555BB9_EE34_485E_878D_D2B7BF154005;
        
        /// <summary>
        /// ID8_5BE0D294_3F17_4E99_AAA9_80FE0DC7AF4C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_5BE0D294_3F17_4E99_AAA9_80FE0DC7AF4C;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
