//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class DoiTuongKiemToan_Load {
        
        /// <summary>
        /// ID8_94F402C1_CCC3_4A93_8D9F_2D24BDB8EE2C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_94F402C1_CCC3_4A93_8D9F_2D24BDB8EE2C;
        
        /// <summary>
        /// ID8_F4018BE5_84AD_4FE2_B3AF_5BC3F5981CEA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_F4018BE5_84AD_4FE2_B3AF_5BC3F5981CEA;
        
        /// <summary>
        /// ID8_18BCCAAE_F688_4D50_98C1_0F1EE034AEA0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_18BCCAAE_F688_4D50_98C1_0F1EE034AEA0;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
