//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class LoaiDoiTuongKiemToan_Load {
        
        /// <summary>
        /// ID8_410D55A8_48D8_4EED_894D_836E24E1E36D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_410D55A8_48D8_4EED_894D_836E24E1E36D;
        
        /// <summary>
        /// ID8_563054B4_4305_4D2D_AE75_8B54F80F56EB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_563054B4_4305_4D2D_AE75_8B54F80F56EB;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
