//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class MucDoRuiRo_Load {
        
        /// <summary>
        /// ID8_F92EA020_7FB3_41CA_A233_8CDFE91D0C77 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_F92EA020_7FB3_41CA_A233_8CDFE91D0C77;
        
        /// <summary>
        /// ID8_7B451BD1_204F_42A1_82B8_37FB9CC3710D control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_7B451BD1_204F_42A1_82B8_37FB9CC3710D;
        
        /// <summary>
        /// ID6_6EED4C06_6D40_4926_BD2B_4685CF47C40C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_6EED4C06_6D40_4926_BD2B_4685CF47C40C;
        
        /// <summary>
        /// ID6_1F9EA2E5_16B2_4080_B907_B195D4A540D6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_1F9EA2E5_16B2_4080_B907_B195D4A540D6;
        
        /// <summary>
        /// ID6_5D0BE3C9_5C9D_4C16_922E_6A1CA752A15C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_5D0BE3C9_5C9D_4C16_922E_6A1CA752A15C;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
