//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class QuyMoDotKiemToan_Load {
        
        /// <summary>
        /// ID8_B041CD82_06B3_46F6_ABC1_897E5FBBF110 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_B041CD82_06B3_46F6_ABC1_897E5FBBF110;
        
        /// <summary>
        /// ID8_61E320B2_1AE9_4ADE_8E09_431CB5F5F697 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_61E320B2_1AE9_4ADE_8E09_431CB5F5F697;
        
        /// <summary>
        /// ID6_DE82AAE4_AE92_4435_B609_6673AA45C62F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_DE82AAE4_AE92_4435_B609_6673AA45C62F;
        
        /// <summary>
        /// ID6_479E464B_0FB8_46D6_BF48_CF7F2DE518AE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_479E464B_0FB8_46D6_BF48_CF7F2DE518AE;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
