//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class RuiRoChinh_Load {
        
        /// <summary>
        /// ID8_8707977E_31B9_4EA4_B016_4D110C0D9F64 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_8707977E_31B9_4EA4_B016_4D110C0D9F64;
        
        /// <summary>
        /// ID8_6B55AA99_3C65_45BF_95C1_5121CA7A3614 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_6B55AA99_3C65_45BF_95C1_5121CA7A3614;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
