//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class RuiRoPhu_Load {
        
        /// <summary>
        /// ID8_98257A5A_8722_422B_8B7A_4D0505104638 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_98257A5A_8722_422B_8B7A_4D0505104638;
        
        /// <summary>
        /// ID8_7E6E277C_A1F7_4BE6_90E6_C2E5F56DCD7B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_7E6E277C_A1F7_4BE6_90E6_C2E5F56DCD7B;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
        
        /// <summary>
        /// ID8_7B8EEC76_550C_46E3_BA02_E22958E5B3E2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_7B8EEC76_550C_46E3_BA02_E22958E5B3E2;
    }
}
