//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class ThuTucKiemToan_Load {
        
        /// <summary>
        /// ID8_4B3FCE9D_5A7E_4DD6_893B_912086B225B2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_4B3FCE9D_5A7E_4DD6_893B_912086B225B2;
        
        /// <summary>
        /// ID8_98F450F3_824E_4BBD_9F9D_6C9845FD8186 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_98F450F3_824E_4BBD_9F9D_6C9845FD8186;
        
        /// <summary>
        /// ID8_2D17E66A_B9EB_4051_ABB4_01CBA54512DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_2D17E66A_B9EB_4051_ABB4_01CBA54512DD;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
