//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class TieuChiDanhGiaXacSuatAnhHuong_Load {
        
        /// <summary>
        /// ID8_5C64F7E2_116A_43A1_A3AE_333213E15B4E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_5C64F7E2_116A_43A1_A3AE_333213E15B4E;
        
        /// <summary>
        /// ID8_31C0688F_D708_4741_941C_1C031D9B6CAE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_31C0688F_D708_4741_941C_1C031D9B6CAE;
        
        /// <summary>
        /// ID8_6667604E_1FB6_48D3_957F_22A8B5681C70 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_6667604E_1FB6_48D3_957F_22A8B5681C70;
        
        /// <summary>
        /// ID8_B07C032D_8B99_405C_BB8C_C4BB8AD88B31 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_B07C032D_8B99_405C_BB8C_C4BB8AD88B31;
        
        /// <summary>
        /// ID8_6DCC915B_C3A8_4F26_A8A5_A3FC2FED9BDD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_6DCC915B_C3A8_4F26_A8A5_A3FC2FED9BDD;
        
        /// <summary>
        /// ID8_E17E9406_5264_442D_B512_C888253D6A8B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_E17E9406_5264_442D_B512_C888253D6A8B;
        
        /// <summary>
        /// ID8_B320D0B7_BEA3_472A_8557_A28B3EAF5DC3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_B320D0B7_BEA3_472A_8557_A28B3EAF5DC3;
        
        /// <summary>
        /// ID8_CFE67746_AF75_4893_BEF5_8AEFE9C1438B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_CFE67746_AF75_4893_BEF5_8AEFE9C1438B;
    }
}
