//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_TDHS.Modules.Lookup {
    
    
    public partial class TieuChiDanhGiaKTV_Load {
        
        /// <summary>
        /// ID8_1AC09A4B_EC8F_4FEB_9908_FFC06D294E25 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_1AC09A4B_EC8F_4FEB_9908_FFC06D294E25;
        
        /// <summary>
        /// ID8_170AE424_36DC_4B5C_A88B_188FA9947EEA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_170AE424_36DC_4B5C_A88B_188FA9947EEA;
        
        /// <summary>
        /// ID8_D7C67D2B_0E3F_4024_8DC0_6387AE7E6A3E control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ID8_D7C67D2B_0E3F_4024_8DC0_6387AE7E6A3E;
        
        /// <summary>
        /// DOCSTATUS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DOCSTATUS;
    }
}
