//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.Lookup.CacDTKT {
    
    
    public partial class RankLoaiDTKT {
        
        /// <summary>
        /// ObjectDataSource1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
        
        /// <summary>
        /// ID8_D156BDD2_ACCB_4985_B95A_1429F44D65B6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ID8_D156BDD2_ACCB_4985_B95A_1429F44D65B6;
        
        /// <summary>
        /// ID6_4A6A8527_1C1C_4526_AE82_5C1EE7FE3B05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_4A6A8527_1C1C_4526_AE82_5C1EE7FE3B05;
        
        /// <summary>
        /// ID6_DF099D26_D6F3_4965_B854_8CC2FE8A37E2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_DF099D26_D6F3_4965_B854_8CC2FE8A37E2;
        
        /// <summary>
        /// ID6_F9A6DBEA_DFD3_4425_A628_C15E18DA997F control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Input.C1WebNumericEdit ID6_F9A6DBEA_DFD3_4425_A628_C15E18DA997F;
        
        /// <summary>
        /// btnThem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnThem;
        
        /// <summary>
        /// dataCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater dataCtrl;
    }
}
