//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPB_KTNB.Modules.UMS.DonViKTNB
{


    public partial class QL_DonViKTNB_Input
    {
    }
}
